# Generated by Django 4.2.1 on 2023-05-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S_directory_DCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Calculater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('count_r', models.IntegerField()),
                ('price_without_NDS', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без НДС')),
                ('NDS', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='НДС')),
                ('price_with_NDS', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена с НДС')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_calculater', to='mains.s_directory_dcreative', verbose_name='Формат размещения')),
            ],
        ),
    ]
