# Generated by Django 4.2.1 on 2023-05-22 07:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_s_directory_dcreative_in_calculater_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=150, verbose_name='Специализация')),
                ('count_doc', models.CharField(max_length=7, verbose_name='Количество докторов')),
                ('coefficient', models.CharField(max_length=4, verbose_name='Коэффициент специализации')),
                ('count_doc_GRP', models.CharField(max_length=7, verbose_name='Коэффициент GRP')),
                ('in_changeauditories', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['speciality'],
            },
        ),
        migrations.AlterField(
            model_name='calculater',
            name='NDS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='calculater',
            name='creative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.s_directory_dcreative', verbose_name='Формат размещения'),
        ),
        migrations.AlterField(
            model_name='calculater',
            name='price_with_NDS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена с НДС'),
        ),
        migrations.AlterField(
            model_name='calculater',
            name='price_without_NDS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена без НДС'),
        ),
        migrations.CreateModel(
            name='ChangeAuditories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mains.auditories', verbose_name='Выбранная аудитория')),
            ],
        ),
    ]
