# Generated by Django 4.2.1 on 2023-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_auditories_alter_calculater_nds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditories',
            name='in_accommodation',
            field=models.BooleanField(default=False),
        ),
    ]
