# Generated by Django 4.2.1 on 2023-05-23 08:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_auditories_in_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('price_before_10000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_before_25000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_after_25000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kpi_sd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=150)),
                ('group', models.IntegerField()),
                ('fte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='auditories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='changeauditories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('count_doc', models.IntegerField()),
                ('season', models.CharField(choices=[('Низкий', -0.25), ('Без сезона', 0), ('Высокий сезон', 0.25)], max_length=13, verbose_name='Выбор сезона')),
                ('season_coeff', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Коэффициент сезонности')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена за единицу')),
                ('count_a', models.IntegerField(null=True, verbose_name='Количество')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_rub', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Скидка в рублях')),
                ('price_not_NDS', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена без НДС')),
                ('price_d', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена с учетом скидки')),
                ('NDS', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='НДС')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена с НДС')),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость за единицу')),
                ('fte', models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grp', models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.service', verbose_name='Формат размещения')),
                ('specialyties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.changeauditories', verbose_name='Специализация врача')),
            ],
        ),
    ]
