# Generated by Django 4.2.1 on 2023-05-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0005_service_alter_auditories_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='count_doc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
