# Generated by Django 4.2.1 on 2023-05-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_alter_accommodation_count_doc_alter_accommodation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='count_a',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='changeauditories',
            name='auditories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_auditories', to='mains.auditories', verbose_name='Выбранная аудитория'),
        ),
    ]
