# Generated by Django 4.2.1 on 2023-05-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0007_alter_accommodation_count_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='season',
            field=models.CharField(choices=[('L', 'Низкий'), ('N', 'Без сезона'), ('H', 'Высокий сезон')], max_length=13, verbose_name='Выбор сезона'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='specialyties',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mains.changeauditories', verbose_name='Специализация врача'),
        ),
        migrations.AlterField(
            model_name='changeauditories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
