# Generated by Django 4.2.1 on 2023-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0008_alter_accommodation_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeauditories',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
