# Generated by Django 4.2.1 on 2023-05-31 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0009_changeauditories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='name_change',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='specialyties',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mains.changeauditories', verbose_name='Специализация врача'),
        ),
    ]
