# Generated by Django 4.2.1 on 2023-06-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0010_accommodation_name_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='specialyties',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mains.changeauditories', verbose_name='Специализация врача'),
        ),
    ]
