# Generated by Django 4.2.1 on 2023-06-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0011_alter_accommodation_specialyties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('doctor', models.CharField(max_length=255)),
                ('count_doc', models.IntegerField()),
                ('accommodation_price_not_NDS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation_price_with_NDS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculator_price_not_NDS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculator_price_with_NDS', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
