# Generated by Django 4.2.1 on 2023-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0013_alter_resulttable_accommodation_price_not_nds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttable',
            name='accommodation_price_not_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='accommodation_price_with_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='calculator_price_not_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='calculator_price_with_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='count_doc',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='doctor',
        ),
        migrations.AddField(
            model_name='resulttable',
            name='name_accommodation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='name_calculater',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='name_change',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='result_list',
            field=models.JSONField(blank=True, null=True, verbose_name=models.CharField(max_length=100)),
        ),
    ]
