# Generated by Django 4.2.1 on 2023-06-06 17:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0014_remove_resulttable_accommodation_price_not_nds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='accommodation_price_not_NDS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='accommodation_price_with_NDS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='calculator_price_not_NDS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='calculator_price_with_NDS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='count_doc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
