# Generated by Django 4.2.1 on 2023-06-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0015_resulttable_accommodation_price_not_nds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttable',
            name='accommodation_price_not_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='accommodation_price_with_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='calculator_price_not_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='calculator_price_with_NDS',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='count_doc',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='result_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
